import { Box, Grid } from '@material-ui/core'
import Head from 'next/head'
import AudioPlayer from '../components/AudioPlayer'
import { useStyles } from './styles'

export default function Home() {
  const classes = useStyles()
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Grid 
          container 
          justifyContent='center'
          className={ classes.root }
        >
          <Grid 
            item 
            xs={12}>
            <Box 
              component='div' 
              className={ classes.audioContainer }>
              <AudioPlayer />
            </Box>
          </Grid>
        </Grid>
      </main>
    </div>
  )
}
